version: "3.9"
services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/employee_management
      - SECRET_KEY=replace_this_in_production
    volumes:
      - .:/app

  mongo:
    image: mongo:5.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=AdminDB@123
      - ME_CONFIG_MONGODB_PORT=27017

volumes:
  mongo_data:
